---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycase-deploy
  labels:
    app: mycase-app
spec:
  selector:
    matchLabels:
      app: mycase-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: mycase-app
    spec:
      containers:
      - name: mycase-app
        image: rskaradag/python:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"